# Theta configuration
storage:
  statePruningInterval: 4
  statePruningRetainedBlocks: 128
p2p:
  port: 16000
  seeds: 3.18.35.120:21000,18.224.234.179:21000,3.18.96.195:21000
rpc:
  enabled: true
log:
  levels: "*:info"
