# Theta configuration
genesis:
  hash: "0x8a6477bded27d5b8ec99d66dfd38e1e926a2ef9ca30009407213d17559bbef19"
storage:
  statePruningRetainedBlocks: 1024
p2p:
  opt: 1
  portL: PORT
  libp2pRendezvous: theta_testnet_sapphire
  libp2pSeeds: /ip4/[VALIDATOR_1_IP]/tcp/[VALIDATOR_1_PORT]/ipfs/12D3KooWDYYjn2eCD3viA8xsE8fhsnhcgptizHiywK8bTfmftpZ6,/ip4/[VALIDATOR_2_IP]/tcp/[VALIDATOR_2_PORT]/ipfs/12D3KooWP7UQM56CoP2ggZNERdQhuJRc8KN1A1iqdPscYJZPsWDZ,/ip4/[VALIDATOR_3_IP]/tcp/[VALIDATOR_3_PORT]/ipfs/12D3KooWAmBXBCRUQmMvzU2Gy48hJRMPPgNtzLVipWz2nUCbcq4C,/ip4/[VALIDATOR_4_IP]/tcp/[VALIDATOR_4_PORT]/ipfs/12D3KooWGK9snBWHR1vXfnGsGFZyRQxLp7z2tPBL29oYAVF1vuPW
rpc:
  enabled: false
log:
  levels: "*:info,guardian:debug"
